### ISSUE TITLE
程序启动时报空指针异常

### ISSUE THREAD

**Issue by lemos1235** [rememberber/WePush#243]
### 现象描述
程序启动报错

### 环境信息

系统版本： archlinux x86_64 Linux 5.5.13-arch2-1

java 版本:  openjdk version "11.0.6" 2020-01-14

### 报错信息

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bulenkov.darcula.DarculaLaf (file:/home/lg/Downloads/WePush-4.2.0/lib/darcula-lnf-1.0.jar) to field javax.swing.text.html.HTMLEditorKit.DEFAULT_STYLES_KEY
WARNING: Please consider reporting this to the maintainers of com.bulenkov.darcula.DarculaLaf
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.bulenkov.iconloader.IconLoader.<clinit>(IconLoader.java:53)
	at com.bulenkov.darcula.DarculaLaf.getDefaults(DarculaLaf.java:97)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)
	at com.fangxuele.tool.push.ui.Init.initTheme(Init.java:111)
	at com.fangxuele.tool.push.App.main(App.java:37)
Caused by: java.lang.NullPointerException
	at com.bulenkov.iconloader.util.UIUtil.initSystemFontData(UIUtil.java:254)
	at com.bulenkov.iconloader.util.JBUI.calculateScaleFactor(JBUI.java:47)
	at com.bulenkov.iconloader.util.JBUI.<clinit>(JBUI.java:33)
	... 6 more
```

[在此填写WePush安装目录下logs文件夹内的报错信息]
![image](https://user-images.githubusercontent.com/23135552/78353081-0f68c200-75dc-11ea-98a8-2c40b7fd4858.png)

**Comment by DevCharly** [comment]
To avoid the message `Illegal reflective access by com.bulenkov.darcula.DarculaLaf` at startup,
and maybe also fix the exception,
you could use FlatLaf (https://github.com/JFormDesigner/FlatLaf).

**Comment by rememberber** [comment]
用最新版试试
