### ISSUE TITLE
不存在 application.setEnabledAboutMenu(false); application.setEnabledPreferencesMenu(false);

### ISSUE THREAD

**Issue by mingtianshi** [rememberber/WePush#264]

**Comment by mingtianshi** [comment]
不存在
application.setEnabledAboutMenu(false);
application.setEnabledPreferencesMenu(false);

所以出现
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.apple.eawt.Application.setEnabledAboutMenu(boolean)'
    at com.fangxuele.tool.push.ui.frame.MainFrame.init(MainFrame.java:59)
    at com.fangxuele.tool.push.App.main(App.java:39)

// Mac系统Dock图标
if (SystemUtil.isMacOs()) {
    Application application = Application.getApplication();
    application.setDockIconImage(UiConsts.IMAGE_LOGO_1024);
    if (!SystemUtil.isMacM1()) {
        application.setEnabledAboutMenu(false);
        application.setEnabledPreferencesMenu(false);
    }

**Comment by rememberber** [comment]
使用最新版试试
